const express=require("express");const cors=require("cors");const path=require("path");const axios=require("axios");const {Pool}=require("pg");require("dotenv").config();
const app=express(),PORT=process.env.PORT||3000,PUBLIC_DIR=path.join(__dirname,"public"),OPENAI_API_KEY=process.env.OPENAI_API_KEY,OPENAI_MODEL=process.env.OPENAI_MODEL||"gpt-5.6-luna",STRATEGY_VERSION="adaptive-v1";
app.use(cors());app.use(express.json({limit:"1mb"}));app.use(express.static(PUBLIC_DIR,{index:"index.html"}));app.get("/",(_req,res)=>res.sendFile(path.join(PUBLIC_DIR,"index.html")));
function databaseUrl(){return process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.POSTGRES_PRISMA_URL||process.env.POSTGRES_URL_NON_POOLING||process.env.NEON_DATABASE_URL||null}
let pool=null,poolUrl=null;
function getPool(){const url=databaseUrl();if(!url)return null;if(!pool||poolUrl!==url){poolUrl=url;pool=new Pool({connectionString:url,ssl:{rejectUnauthorized:false},max:3,idleTimeoutMillis:10000,connectionTimeoutMillis:5000})}return pool}
function dbReady(){return Boolean(databaseUrl())}
const TF={"1m":{interval:"1m",range:"7d"},"3m":{interval:"1m",range:"7d"},"5m":{interval:"5m",range:"1mo"},"15m":{interval:"15m",range:"1mo"},"1h":{interval:"60m",range:"3mo"}};
function aggregate3m(candles){const out=[];for(const c of candles){const bucket=Math.floor(new Date(c.timestamp).getTime()/180000)*180000;let g=out[out.length-1];if(!g||g.bucket!==bucket){g={bucket,timestamp:new Date(bucket).toISOString(),open:c.open,high:c.high,low:c.low,close:c.close,volume:c.volume||0};out.push(g)}else{g.high=Math.max(g.high,c.high);g.low=Math.min(g.low,c.low);g.close=c.close;g.volume+=c.volume||0}}return out.map(({bucket,...c})=>c)}
async function yahoo(timeframe){const cfg=TF[timeframe],symbol="GC=F",url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}`;const response=await axios.get(url,{params:{interval:cfg.interval,range:cfg.range,includePrePost:true,events:"div,splits"},timeout:10000,headers:{"User-Agent":"Mozilla/5.0 RB-Gold-Sniper/3.1"}});const result=response.data?.chart?.result?.[0];if(!result)throw new Error("Yahoo Finance não devolveu dados do ouro (GC=F)");const q=result.indicators?.quote?.[0]||{};let candles=(result.timestamp||[]).map((ts,i)=>({timestamp:new Date(ts*1000).toISOString(),open:Number(q.open?.[i]),high:Number(q.high?.[i]),low:Number(q.low?.[i]),close:Number(q.close?.[i]),volume:Number(q.volume?.[i]||0)})).filter(c=>[c.open,c.high,c.low,c.close].every(Number.isFinite));if(timeframe==="3m")candles=aggregate3m(candles);candles=candles.slice(-300);if(!candles.length)throw new Error("Yahoo Finance não devolveu candles válidos para GC=F");const meta=result.meta||{},last=candles[candles.length-1],livePrice=Number(meta.regularMarketPrice);if(Number.isFinite(livePrice))last.close=livePrice;return{source:"Yahoo Finance — Gold Futures (GC=F), fallback sem API key",symbol,timeframe,candles,last,meta}}
async function yahooQuote(symbol){const url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}`;const response=await axios.get(url,{params:{interval:"1m",range:"1d",includePrePost:true},timeout:10000,headers:{"User-Agent":"Mozilla/5.0 RB-Gold-Sniper/3.1"}});const result=response.data?.chart?.result?.[0];if(!result)throw new Error(`Yahoo não devolveu a cotação de ${symbol}`);const meta=result.meta||{},price=Number(meta.regularMarketPrice),ts=Number(meta.regularMarketTime||0);if(!Number.isFinite(price))throw new Error(`Yahoo não devolveu preço válido de ${symbol}`);return{symbol,price,timestamp:ts?new Date(ts*1000).toISOString():new Date().toISOString(),delayedBy:Number(meta.exchangeDataDelayedBy||0)}}
async function spotReference(){const futures=await yahooQuote("GC=F");return{calibrated:false,offset:0,futures,spot:null,source:"Yahoo Finance GC=F — referência de recurso; feed spot direto indisponível"}}
async function market(timeframe){if(!TF[timeframe])throw new Error("Timeframe inválido");return yahoo(timeframe)}
function cleanTrade(input){if(!input||!["BUY","SELL"].includes(input.type))throw new Error("Tipo de trade inválido");if(!Number.isFinite(Number(input.price))||!Number.isFinite(Number(input.tp))||!Number.isFinite(Number(input.sl)))throw new Error("Entrada, TP e SL são obrigatórios");return{signalKey:String(input.signalKey||`${input.type}-${Number(input.price).toFixed(2)}-${String(input.time||"").slice(0,16)}`).slice(0,180),type:input.type,createdAt:input.time||new Date().toISOString(),entryPrice:Number(input.price),tp:Number(input.tp),sl:Number(input.sl),rr:Number.isFinite(Number(input.rr))?Number(input.rr):null,confidence:Number.isFinite(Number(input.confidence))?Number(input.confidence):null,rsi:Number.isFinite(Number(input.rsi))?Number(input.rsi):null,atr:Number.isFinite(Number(input.atr))?Number(input.atr):null,ema20:Number.isFinite(Number(input.ema20))?Number(input.ema20):null,ema50:Number.isFinite(Number(input.ema50))?Number(input.ema50):null,ema200:Number.isFinite(Number(input.ema200))?Number(input.ema200):null,support:Number.isFinite(Number(input.support))?Number(input.support):null,resistance:Number.isFinite(Number(input.resistance))?Number(input.resistance):null,trend3:input.trend3||null,trend5:input.trend5||null,trend15:input.trend15||null,trend1:input.trend1||null,score:Number.isFinite(Number(input.score))?Number(input.score):null,source:input.source||"GC=F fallback",timeframe:input.timeframe||"1m",strategyVersion:input.strategyVersion||STRATEGY_VERSION,filters:input.filters||{},reasons:input.reasons||[],rejectionReasons:input.rejectionReasons||[],rawSignal:input}}
async function saveTrade(input){const db=getPool();if(!db)return{saved:false,reason:"DATABASE_URL não configurada"};const t=cleanTrade(input);const q=`INSERT INTO sniper_trades (signal_key,created_at,type,status,entry_price,tp,sl,rr,confidence,rsi,atr,ema20,ema50,ema200,support,resistance,trend3,trend5,trend15,trend1,score,source,timeframe,strategy_version,filters,reasons,rejection_reasons,raw_signal) VALUES ($1,$2,$3,'ALERTA',$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28) ON CONFLICT (signal_key) DO NOTHING RETURNING id,created_at,status`;const v=[t.signalKey,t.createdAt,t.type,t.entryPrice,t.tp,t.sl,t.rr,t.confidence,t.rsi,t.atr,t.ema20,t.ema50,t.ema200,t.support,t.resistance,t.trend3,t.trend5,t.trend15,t.trend1,t.score,t.source,t.timeframe,t.strategyVersion,JSON.stringify(t.filters),JSON.stringify(t.reasons),JSON.stringify(t.rejectionReasons),JSON.stringify(t.rawSignal)];const r=await db.query(q,v);return{saved:true,inserted:r.rowCount>0,id:r.rows[0]?.id||null}}
async function getTrades(limit=200){const db=getPool();if(!db)return[];const n=Math.min(Math.max(Number(limit)||200,1),1000);const r=await db.query(`SELECT id,signal_key AS "signalKey",created_at AS "time",resolved_at AS "resolvedAt",type,status,entry_price AS price,tp,sl,rr,confidence,rsi,atr,ema20,ema50,ema200,support,resistance,trend3,trend5,trend15,trend1,score,source,timeframe,max_price AS "maxPrice",min_price AS "minPrice",outcome_reason AS "outcomeReason",strategy_version AS "strategyVersion",filters,reasons,rejection_reasons AS "rejectionReasons" FROM sniper_trades ORDER BY created_at DESC LIMIT $1`,[n]);return r.rows}
async function resolveTrades(){const db=getPool();if(!db)return{resolved:0};const open=(await db.query(`SELECT id,type,created_at,entry_price,tp,sl FROM sniper_trades WHERE status='ALERTA' ORDER BY created_at ASC LIMIT 500`)).rows;if(!open.length)return{resolved:0};const m=await market("1m");let resolved=0;for(const t of open){const created=new Date(t.created_at).getTime(),candles=m.candles.filter(c=>new Date(c.timestamp).getTime()>created);let result=null,resolvedAt=null,reason=null,maxPrice=null,minPrice=null;for(const c of candles){maxPrice=maxPrice===null?c.high:Math.max(maxPrice,c.high);minPrice=minPrice===null?c.low:Math.min(minPrice,c.low);const tpHit=t.type==='BUY'?c.high>=t.tp:c.low<=t.tp,slHit=t.type==='BUY'?c.low<=t.sl:c.high>=t.sl;if(tpHit&&slHit){result='EXPIRADA';reason='TP e SL atingidos na mesma vela de 1m; resultado ambíguo';resolvedAt=c.timestamp;break}if(tpHit){result='WIN';reason='TP atingido';resolvedAt=c.timestamp;break}if(slHit){result='LOSS';reason='SL atingido';resolvedAt=c.timestamp;break}}if(!result&&Date.now()-created>=6*60*60*1000){result='EXPIRADA';reason='Sem TP/SL após 6 horas';resolvedAt=new Date().toISOString()}if(result){await db.query(`UPDATE sniper_trades SET status=$1,resolved_at=$2,max_price=$3,min_price=$4,outcome_reason=$5 WHERE id=$6`,[result,resolvedAt,maxPrice,minPrice,reason,t.id]);resolved++}}return{resolved}}
function extractAIText(d){if(typeof d?.output_text==='string'&&d.output_text.trim())return d.output_text.trim();const p=[];for(const i of Array.isArray(d?.output)?d.output:[])for(const c of Array.isArray(i?.content)?i.content:[]){if(typeof c?.text==='string')p.push(c.text);if(typeof c?.value==='string')p.push(c.value)}return p.join("\n").trim()}function parseConfidence(v){if(typeof v==='number'&&Number.isFinite(v))return v;const m=String(v??"").replace(",",".").match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):NaN}
async function aiOpinion(signal,marketData){if(!OPENAI_API_KEY)return{available:false,confidence:null,opinion:"NEUTRO",note:"IA indisponível"};const payload={technicalSignal:signal?.type||"WAIT",technicalConfidence:signal?.confidence??null,price:signal?.price??null,tp:signal?.tp??null,sl:signal?.sl??null,rr:signal?.rr??null,rsi:signal?.rsi??null,atr:signal?.atr??null,ema20:signal?.ema20??null,ema50:signal?.ema50??null,ema200:signal?.ema200??null,support:signal?.support??null,resistance:signal?.resistance??null,trends:{m3:signal?.trend3,m5:signal?.trend5,m15:signal?.trend15,h1:signal?.trend1},filters:signal?.filters||{},rejectionReasons:signal?.rejectionReasons||[],lastCandles:(marketData||[]).slice(-12).map(c=>({t:c.timestamp,o:c.open,h:c.high,l:c.low,c:c.close}))};const response=await axios.post("https://api.openai.com/v1/responses",{model:OPENAI_MODEL,input:[{role:"system",content:[{type:"input_text",text:"És um analista auxiliar do RB Gold Sniper. Dá apenas um parecer independente sobre XAUUSD. NÃO alteres, substituas ou cries o sinal técnico. Não inventes dados. Devolve JSON válido com confidence (0-100), opinion (BUY, SELL ou NEUTRO) e note (máximo 140 caracteres)."}]},{role:"user",content:[{type:"input_text",text:JSON.stringify(payload)}]}],text:{format:{type:"json_object"}},max_output_tokens:180},{headers:{Authorization:`Bearer ${OPENAI_API_KEY}`,"Content-Type":"application/json"},timeout:15000});const text=extractAIText(response.data);if(!text)throw new Error("A IA não devolveu texto");let parsed;try{parsed=JSON.parse(text)}catch{const json=text.match(/\{[\s\S]*\}/)?.[0];if(!json)throw new Error("A IA devolveu uma resposta não-JSON");parsed=JSON.parse(json)}const rawConfidence=parseConfidence(parsed?.confidence);if(!Number.isFinite(rawConfidence))throw new Error("A IA não devolveu confiança numérica");return{available:true,confidence:Math.max(0,Math.min(100,Math.round(rawConfidence))),opinion:["BUY","SELL","NEUTRO"].includes(String(parsed?.opinion||"").toUpperCase())?String(parsed.opinion).toUpperCase():"NEUTRO",note:String(parsed?.note||"").slice(0,140)}}
app.get("/api/health",async(_req,res)=>{try{const m=await market("1m");res.json({status:"OK",marketConnected:true,historyDatabase:dbReady(),source:m.source,symbol:m.symbol,aiEnabled:Boolean(OPENAI_API_KEY),mode:"ALERTAS",timestamp:new Date().toISOString()})}catch(e){res.status(503).json({status:"DEGRADED",marketConnected:false,historyDatabase:dbReady(),aiEnabled:Boolean(OPENAI_API_KEY),mode:"ALERTAS",error:e.message})}});
app.get("/api/oanda-reference",async(_req,res)=>{try{res.set("Cache-Control","no-store");res.json({success:true,...await spotReference()})}catch(e){res.status(502).json({success:false,calibrated:false,offset:0,error:e.message})}});
app.get("/api/market",async(req,res)=>{try{const m=await market(String(req.query.timeframe||"1m"));res.json({success:true,source:m.source,symbol:m.symbol,timeframe:m.timeframe,candles:m.candles,price:m.last.close,bid:null,ask:null,spread:null,timestamp:m.last.timestamp,quoteTimestamp:m.meta?.regularMarketTime?new Date(Number(m.meta.regularMarketTime)*1000).toISOString():m.last.timestamp,delayedBy:Number(m.meta?.exchangeDataDelayedBy||0)})}catch(e){res.status(502).json({success:false,error:"Não foi possível obter dados do ouro.",details:e.message})}});
app.post("/api/ai/opinion",async(req,res)=>{try{res.json({success:true,...await aiOpinion(req.body?.signal,req.body?.candles),model:OPENAI_MODEL})}catch(e){console.error("AI opinion error:",e.message);res.status(502).json({success:false,available:Boolean(OPENAI_API_KEY),confidence:null,opinion:"NEUTRO",note:e.message||"IA indisponível neste momento"})}});
app.post("/api/trades",async(req,res)=>{try{const r=await saveTrade(req.body);res.status(r.saved?200:503).json({success:r.saved,...r})}catch(e){res.status(400).json({success:false,error:e.message})}});
app.get("/api/trades",async(req,res)=>{try{res.json({success:true,database:dbReady(),trades:await getTrades(req.query.limit)})}catch(e){res.status(503).json({success:false,error:e.message,trades:[]})}});
app.post("/api/trades/resolve",async(_req,res)=>{try{res.json({success:true,...await resolveTrades()})}catch(e){res.status(503).json({success:false,error:e.message})}});
app.get("/api/trades/stats",async(_req,res)=>{try{const db=getPool();if(!db)return res.json({success:true,database:false,total:0,open:0,wins:0,losses:0,expired:0});const r=await db.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='ALERTA')::int open,COUNT(*) FILTER(WHERE status='WIN')::int wins,COUNT(*) FILTER(WHERE status='LOSS')::int losses,COUNT(*) FILTER(WHERE status='EXPIRADA')::int expired FROM sniper_trades`);res.json({success:true,database:true,...r.rows[0]})}catch(e){res.status(503).json({success:false,error:e.message})}});
app.listen(PORT,()=>console.log(`RB Gold Sniper running on port ${PORT}`));
