const axios=require("axios");
const BASE="https://api.binance.com/api/v3";
const SYMBOL="PAXGUSDT";
const TF={"1m":"1m","3m":"3m","5m":"5m","15m":"15m","1h":"1h"};
const cache=new Map(),inflight=new Map(),CACHE_MS=8000;
function valid(c){return [c.open,c.high,c.low,c.close].every(Number.isFinite)&&c.open>0&&c.high>=Math.max(c.open,c.close)&&c.low<=Math.min(c.open,c.close)&&c.high>=c.low}
function clean(a){return a.filter(valid).sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp)).filter((c,i,s)=>i===0||c.timestamp!==s[i-1].timestamp)}
function candles(rows){return clean(rows.map(x=>({timestamp:new Date(Number(x[0])).toISOString(),open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[5]||0),complete:Number(x[6])<=Date.now()})))}
async function request(url,params){let last;for(let i=0;i<3;i++){try{return await axios.get(url,{params,timeout:10000,headers:{Accept:"application/json","User-Agent":"RB-Gold-Sniper/1.0"}})}catch(e){last=e;if(i<2)await new Promise(r=>setTimeout(r,400*(i+1)))}}throw last}
async function getMarket(timeframe){if(!TF[timeframe])throw new Error("Timeframe inválido");const key=`binance:${timeframe}`,hit=cache.get(key);if(hit&&Date.now()-hit.t<CACHE_MS)return hit.v;if(inflight.has(key))return inflight.get(key);const p=(async()=>{const r=await request(`${BASE}/klines`,{symbol:SYMBOL,interval:TF[timeframe],limit:1000});if(!Array.isArray(r.data)||!r.data.length)throw new Error("Binance não devolveu candles PAXGUSDT");const cs=candles(r.data).slice(-300);if(cs.length<50)throw new Error(`Binance devolveu poucos candles (${cs.length})`);const last=cs.at(-1),age=Math.max(0,Date.now()-Date.parse(last.timestamp));const out={success:true,source:"Binance PAXG/USDT — ouro spot (proxy)",symbol:"PAXG/USDT",displaySymbol:"OANDA:XAUUSD",timeframe,candles:cs,last,price:last.close,delayedBy:Math.round(age/1000),candleTimestamp:last.timestamp,quoteTimestamp:last.timestamp,candleAgeSec:Math.round(age/1000),stale:age>{"1m":150,"3m":360,"5m":660,"15m":1860,"1h":7260}[timeframe]*1000,oandaLive:false,feedNotice:"Análise automática por PAXG/USDT; TradingView mostra OANDA:XAUUSD"};cache.set(key,{t:Date.now(),v:out});inflight.delete(key);return out})().catch(e=>{inflight.delete(key);throw e});inflight.set(key,p);return p}
async function handler(req,res){res.setHeader("Cache-Control","no-store,max-age=0");try{const tf=String(req.query.timeframe||"1m"),m=await getMarket(tf);res.status(200).json(m)}catch(e){console.error("MARKET ERROR",e.message);res.status(502).json({success:false,error:"Falha no feed de ouro",details:e.message,source:"Binance PAXG/USDT"})}}
handler.getMarket=getMarket;module.exports=handler;