const axios=require("axios");
const KRAKEN_BASE="https://api.kraken.com/0/public";
const BINANCE_BASE="https://api.binance.com/api/v3";
const PAIR="PAXGUSD";
const BINANCE_PAIR="PAXGUSDT";
const TF={"1m":{interval:1,aggregate:null},"3m":{interval:1,aggregate:3},"5m":{interval:5,aggregate:null},"15m":{interval:15,aggregate:null},"1h":{interval:60,aggregate:null}};
const cache=new Map(),inflight=new Map(),CACHE_MS=8000;
function validCandle(c){const v=[c.open,c.high,c.low,c.close];return v.every(Number.isFinite)&&v.every(x=>x>0&&x<100000)&&c.high>=Math.max(c.open,c.close)&&c.low<=Math.min(c.open,c.close)&&c.high>=c.low}
function sanitize(a){return a.filter(validCandle).sort((x,y)=>Date.parse(x.timestamp)-Date.parse(y.timestamp)).filter((c,i,s)=>i===0||Date.parse(c.timestamp)>Date.parse(s[i-1].timestamp))}
function aggregate(a,minutes){const size=minutes*60000,out=[];for(const c of a){const bucket=Math.floor(Date.parse(c.timestamp)/size)*size;let g=out[out.length-1];if(!g||g.bucket!==bucket){g={bucket,timestamp:new Date(bucket).toISOString(),open:c.open,high:c.high,low:c.low,close:c.close,volume:c.volume||0,complete:c.complete!==false}}else{g.high=Math.max(g.high,c.high);g.low=Math.min(g.low,c.low);g.close=c.close;g.volume+=(c.volume||0);g.complete=g.complete&&c.complete!==false}}return out.map(({bucket,...c})=>c).filter(validCandle)}
async function cached(key,fn){const hit=cache.get(key);if(hit&&Date.now()-hit.time<CACHE_MS)return hit.value;if(inflight.has(key))return inflight.get(key);const p=Promise.resolve().then(fn).then(v=>{cache.set(key,{time:Date.now(),value:v});inflight.delete(key);return v}).catch(e=>{inflight.delete(key);throw e});inflight.set(key,p);return p}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function request(url,config={},attempts=3){let last;for(let i=0;i<attempts;i++){try{return await axios.get(url,{...config,timeout:10000,headers:{"User-Agent":"RB-Gold-Sniper/1.0",Accept:"application/json",...(config.headers||{})}})}catch(e){last=e;if(i<attempts-1)await sleep(500*(i+1))}}throw last}
function resultCandles(rows){return sanitize(rows.map(x=>({timestamp:new Date(Number(x[0])*1000).toISOString(),open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[6]||0),complete:true})))}
async function fetchKraken(timeframe){const cfg=TF[timeframe];const r=await request(`${KRAKEN_BASE}/OHLC`,{params:{pair:PAIR,interval:cfg.interval}});if(r.data?.error?.length)throw new Error(`Kraken: ${r.data.error.join(", ")}`);const key=Object.keys(r.data?.result||{}).find(k=>k!=="last");const rows=key?r.data.result[key]:null;if(!Array.isArray(rows))throw new Error("Kraken não devolveu candles PAXG/USD");let candles=resultCandles(rows);if(cfg.aggregate)candles=aggregate(candles,cfg.aggregate);candles=sanitize(candles).slice(-300);if(candles.length<50)throw new Error(`Kraken: poucos candles válidos (${candles.length})`);return build(candles,timeframe,"Kraken PAXG/USD — proxy de ouro spot")}
async function fetchBinance(timeframe){const cfg=TF[timeframe];const interval=timeframe==="3m"?"1m":({"1m":"1m","5m":"5m","15m":"15m","1h":"1h"}[timeframe]);const r=await request(`${BINANCE_BASE}/klines`,{params:{symbol:BINANCE_PAIR,interval,limit:1000}});if(!Array.isArray(r.data))throw new Error("Binance não devolveu candles PAXG/USDT");let candles=resultCandles(r.data);if(cfg.aggregate)candles=aggregate(candles,cfg.aggregate);candles=sanitize(candles).slice(-300);if(candles.length<50)throw new Error(`Binance: poucos candles válidos (${candles.length})`);return build(candles,timeframe,"Binance PAXG/USDT — proxy de ouro spot")}
function build(candles,timeframe,source){const last=candles.at(-1),age=Math.max(0,Date.now()-Date.parse(last.timestamp));const staleLimit={"1m":150,"3m":360,"5m":660,"15m":1860,"1h":7260}[timeframe]||150;return{success:true,source,symbol:source.startsWith("Binance")?"PAXG/USDT":"PAXG/USD",displaySymbol:"OANDA:XAUUSD",timeframe,candles,last,price:last.close,delayedBy:Math.round(age/1000),candleTimestamp:last.timestamp,quoteTimestamp:last.timestamp,candleAgeSec:Math.round(age/1000),stale:age>staleLimit*1000,oandaLive:false,dataQuality:{valid:true,invalidRemoved:0},feedNotice:"Sem token OANDA — análise automática por proxy PAXG; gráfico visual OANDA:XAUUSD"}}
async function getMarket(timeframe){if(!TF[timeframe])throw new Error("Timeframe inválido");return cached(`gold:${timeframe}`,async()=>{try{return await fetchKraken(timeframe)}catch(e1){try{return await fetchBinance(timeframe)}catch(e2){throw new Error(`${e1.message} | ${e2.message}`)}}})}
async function handler(req,res){res.setHeader("Cache-Control","no-store, max-age=0");try{const timeframe=String(req.query.timeframe||"1m"),m=await getMarket(timeframe);res.json({success:true,...m,price:m.price??m.last.close,quoteTimestamp:m.quoteTimestamp??m.last.timestamp})}catch(e){console.error("MARKET ERROR",e.message);res.status(502).json({success:false,error:"Não foi possível obter dados do ouro",details:e.message,source:"PAXG proxy (Kraken/Binance)"})}}
handler.getMarket=getMarket;module.exports=handler;